"""Generate HTML documentation with Mermaid diagrams from TOML architecture files.

Outputs:
- docs/html/governed-arch/architecture-full.html   (top-level module dependencies)
- docs/html/governed-arch/<safe-name>.html         (per-module: submodule + public_api + interface locks)
"""
import tomllib
import json
import html
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path.cwd()
ASSETS_DIR = PROJECT_ROOT / "docs" / "html" / "governed-arch"
ARCHITECTURE_FILE = PROJECT_ROOT / "architecture.toml"

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} - Architectural Governance</title>
    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.5; color: #333; max-width: 1100px; margin: 0 auto; padding: 15px; background-color: #fcfcfc; }}
        h1 {{ border-bottom: 2px solid #eee; padding-bottom: 8px; margin-bottom: 15px; color: #1a1a1a; font-size: 1.8em; }}
        h2 {{ margin-top: 25px; margin-bottom: 12px; border-left: 4px solid #8E24AA; padding-left: 12px; color: #4A148C; background: #F3E5F5; padding-top: 4px; padding-bottom: 4px; font-size: 1.4em; }}
        h3 {{ margin-top: 20px; margin-bottom: 10px; color: #0D47A1; border-bottom: 1px solid #e3f2fd; padding-bottom: 4px; font-size: 1.2em; }}
        p {{ margin: 8px 0; }}
        .mermaid {{ 
            background: white; 
            padding: 15px; 
            border-radius: 6px; 
            border: 1px solid #ddd; 
            margin: 15px auto; 
            box-shadow: 0 1px 3px rgba(0,0,0,0.05); 
            text-align: center;
            max-width: 100%;
        }}
        .mermaid svg {{
            max-width: 100%;
        }}
        table {{ width: 100%; border-collapse: collapse; margin: 12px 0; background: white; box-shadow: 0 1px 2px rgba(0,0,0,0.1); }}
        th, td {{ text-align: left; padding: 6px 10px; border-bottom: 1px solid #eee; }}
        th {{ background-color: #f8f9fa; font-weight: 600; color: #444; }}
        .badge {{ display: inline-block; padding: 1px 8px; border-radius: 10px; font-size: 0.85em; font-weight: 500; }}
        .badge-param {{ background-color: #E3F2FD; color: #0D47A1; font-family: monospace; }}
        .badge-type {{ background-color: #E8F5E9; color: #1B5E20; font-family: monospace; }}
        .lock-reason {{ background-color: #FFF3E0; border-left: 4px solid #FB8C00; padding: 10px; margin: 12px 0; font-style: italic; border-radius: 0 4px 4px 0; }}
        .badge-gate {{ background-color: #E3F2FD; color: #0D47A1; font-family: monospace; }}
        .badge-p0 {{ background-color: #FFEBEE; color: #B71C1C; font-family: monospace; }}
        .badge-p1 {{ background-color: #FFF3E0; color: #E65100; font-family: monospace; }}
        .badge-p2 {{ background-color: #FFF8E1; color: #F57F17; font-family: monospace; }}
        .badge-p3 {{ background-color: #ECEFF1; color: #546E7A; font-family: monospace; }}
        .design-card {{ background: #fff; border: 1px solid #eee; border-left: 4px solid #1E88E5; padding: 10px 14px; border-radius: 6px; margin-bottom: 10px; }}
        .design-card p {{ margin: 6px 0 0; }}
        .design-card-refs {{ margin-top: 6px; font-size: 0.9em; }}
        .design-ref {{ text-decoration: none; }}
        .design-ref code {{ color: #0D47A1; background: #E3F2FD; padding: 1px 4px; border-radius: 4px; }}
        .invariant-id {{ font-family: monospace; color: #d63384; font-weight: bold; background: #fdf2f8; padding: 1px 5px; border-radius: 4px; }}
        .spec-box {{ background: #fff; border: 1px solid #eee; padding: 12px; border-radius: 6px; margin-bottom: 15px; }}
        code {{ font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace; background: #f4f4f4; padding: 1px 3px; border-radius: 4px; font-size: 0.9em; }}
        ul {{ padding-left: 18px; margin: 8px 0; }}
        li {{ margin-bottom: 4px; }}
        .footer {{ margin-top: 40px; text-align: center; color: #888; font-size: 0.8em; border-top: 1px solid #eee; padding-top: 15px; }}
    </style>
</head>
<body>
    <h1>{header}</h1>
    
    <div class="intro">
        <p>{description}</p>
    </div>

    {content_sections}

    <div class="footer">
        Generated by <code>generate_diagrams.py</code> based on TOML governance files.
        <br/>Last updated: {timestamp}
    </div>

    <script>
        mermaid.initialize({{ 
            startOnLoad: true, 
            theme: 'neutral',
            securityLevel: 'loose',
            themeVariables: {{
                fontSize: '16px',
                fontFamily: '"SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace',
                primaryColor: '#f3f3f3',
                lineColor: '#666'
            }},
            flowchart: {{ 
                useMaxWidth: true,
                htmlLabels: true,
                curve: 'basis'
            }}
        }});
    </script>
</body>
</html>
"""

# Mermaid IDs cannot contain "/", ".", or "-". Use a deterministic scheme.
def safe_id(name: str) -> str:
    return name.replace("/", "_").replace(".", "_").replace("-", "_")


class SectionCounter:
    def __init__(self, start=1):
        self.count = start
    
    def next(self):
        val = self.count
        self.count += 1
        return val


# ── Mermaid Generation ──────────────────────────────────────────────

def _get_dynamic_font_size(node_count: int, is_internal: bool = False) -> str:
    """
    Dynamic font size to compensate for Mermaid's auto-scaling.
    4-tier staircase (unified internal/external):
    - Small (<=5): 16px
    - Medium (6-8): 20px
    - Large (9-12): 28px
    - X-Large (>12): 52px
    """
    if node_count <= 5:
        return "16px"
    elif node_count <= 8:
        return "20px"
    elif node_count <= 12:
        return "28px"
    else:
        return "64px"


def _load_architecture() -> dict:
    with open(ARCHITECTURE_FILE, "rb") as f:
        return tomllib.load(f)


def _load_module_toml(module_dir: Path) -> dict:
    """Load a single module's module.toml. Returns {} if absent."""
    mt = module_dir / "module.toml"
    if not mt.exists():
        return {}
    with open(mt, "rb") as f:
        return tomllib.load(f)


def _get_timestamp() -> str:
    import datetime
    return datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def esc(value: Any) -> str:
    if value is None:
        return ""
    return html.escape(str(value), quote=True)


def esc_br(value: Any) -> str:
    return esc(value).replace("\n", "<br/>")


def generate_architecture_full_mmd(arch: dict) -> str:
    """Top-level module dependency graph from architecture.toml [module.*]."""
    modules = arch.get("module", {})
    if not modules:
        return ""

    node_count = len(modules)
    font_size = _get_dynamic_font_size(node_count)

    lines = ["graph TD", "    %% Top-Level Architecture (Design Intent)"]
    for mod_name, cfg in modules.items():
        desc = cfg.get("description", "")
        if desc:
            desc_lines = [l.strip() for l in desc.splitlines() if l.strip()]
            non_header_lines = [l for l in desc_lines if not (l.startswith("[") and l.endswith("]"))]
            desc = non_header_lines[0] if non_header_lines else desc_lines[0]
        if len(desc) > 24:
            desc = desc[:22] + "…"
        lines.append(
            f'    {safe_id(mod_name)}["<b>{mod_name}</b><br/>'
            f'<small><i>{desc}</i></small>"]:::module'
        )

    lines.append("\n    %% Declared dependencies")
    for mod_name, cfg in modules.items():
        for dep in cfg.get("depends_on", []):
            if dep in modules:
                lines.append(f"    {safe_id(mod_name)} --> {safe_id(dep)}")

    lines.append(f"\n    classDef module fill:#F3E5F5,stroke:#8E24AA,"
                 f"stroke-width:2px,color:#4A148C,font-size:{font_size},font-weight:bold;")
    return "\n".join(lines)


def format_metadata_section(mod_toml: dict, counter: SectionCounter) -> str:
    """Format the [module] section metadata into HTML."""
    module_meta = mod_toml.get("module", {})
    if not module_meta:
        return ""
    
    sections = [f"<h2>{counter.next()}. Responsibility & Data Flow</h2>"]
    
    if "description" in module_meta:
        desc = esc_br(module_meta["description"])
        sections.append(f"<h3>Responsibility</h3><p>{desc}</p>")
    
    consumers = module_meta.get("consumers", [])
    if consumers:
        sections.append("<h3>Consumers</h3><ul>")
        for c in consumers:
            sections.append(f"<li>{esc(c)}</li>")
        sections.append("</ul>")
    
    data_flow = module_meta.get("data_flow", "")
    if data_flow:
        df_html = esc_br(data_flow)
        sections.append(f"<h3>Data Flow</h3><p>{df_html}</p>")
        
    return "".join(sections)


def generate_module_internal_mmd(module_name: str, mod_toml: dict) -> str:
    """Diagram for internal submodule dependencies."""
    module_dir = PROJECT_ROOT / module_name
    # Use submodules list for discovery if available, else fallback to keys of submodule section
    entities = mod_toml.get("module", {}).get("submodules", [])
    sub_rules = mod_toml.get("submodule", {})
    
    if not entities and not sub_rules:
        return ""

    all_entities = set(entities) | set(sub_rules.keys())
    external_entities = set()
    for v in sub_rules.values():
        for dep in v.get("depends_on", []):
            all_entities.add(dep)
        for dep in v.get("internal_depends", []):
            all_entities.add(dep)
        for dep in v.get("external_depends", []):
            external_entities.add(dep)

    node_count = len(all_entities) + len(external_entities)
    font_size = _get_dynamic_font_size(node_count, is_internal=True)

    lines = [f"graph TD", f"    %% {module_name} — Architecture & Dependencies"]

    def label(e: str) -> str:
        if e.endswith(".py"): return e
        if (module_dir / e).is_dir(): return e + "/"
        return e

    for e in sorted(all_entities):
        eid = f"{safe_id(module_name)}_sub_{safe_id(e)}"
        lines.append(f"    {eid}[\"{label(e)}\"]:::internal")

    # Edges
    for src, cfg in sub_rules.items():
        deps = list(cfg.get("depends_on", [])) + list(cfg.get("internal_depends", []))
        for dep in deps:
            src_id = f"{safe_id(module_name)}_sub_{safe_id(src)}"
            dep_id = f"{safe_id(module_name)}_sub_{safe_id(dep)}"
            lines.append(f"    {src_id} --> {dep_id}")
            
        # Draw external_depends as dashed lines to external nodes
        ext_deps = list(cfg.get("external_depends", []))
        for dep in ext_deps:
            src_id = f"{safe_id(module_name)}_sub_{safe_id(src)}"
            dep_id = f"{safe_id(module_name)}_ext_{safe_id(dep)}"
            if dep_id not in lines:
                lines.append(f"    {dep_id}[\"<small><i>{dep}</i></small>\"]:::external")
            lines.append(f"    {src_id} -.-> {dep_id}")


        lines.append(f"\n    classDef internal fill:#E3F2FD,stroke:#1E88E5,stroke-width:2px,color:#0D47A1,font-size:{font_size};")
    lines.append(f"    classDef external fill:#FFF3E0,stroke:#FB8C00,stroke-width:2px,stroke-dasharray:5 5,color:#E65100,font-size:{font_size};")
    return "\n".join(lines)


def generate_module_external_mmd(module_name: str, arch: dict) -> str:
    """Diagram for external module-level dependencies."""
    external_deps = [d for d in get_module_depends_on(module_name, arch) if d != module_name]
    if not external_deps:
        return ""

    node_count = len(external_deps) + 1
    mod_font_size = _get_dynamic_font_size(node_count)
    # External nodes use a slightly smaller font than the primary module node
    ext_font_size = _get_dynamic_font_size(node_count, is_internal=True)

    lines = [f"graph TD", f"    %% {module_name} — External Dependencies"]
    
    # Root node for the current module
    lines.append(f"    {safe_id(module_name)}[\"<b>{module_name}</b>\"]:::module")

    for dep in external_deps:
        lines.append(f"    {safe_id(module_name)} --> {safe_id(dep)}")
        lines.append(f"    {safe_id(dep)}:::external")

    lines.append(f"\n    classDef module fill:#F3E5F5,stroke:#8E24AA,stroke-width:2px,color:#4A148C,font-size:{mod_font_size},font-weight:bold;")
    lines.append(f"    classDef external fill:#FFF3E0,stroke:#FB8C00,stroke-width:2px,stroke-dasharray:5 5,color:#E65100,font-size:{ext_font_size};")

    return "\n".join(lines)


# ── HTML Content Formatting ────────────────────────────────────────

class SectionCounter:
    def __init__(self, start=1):
        self.count = start
    
    def next(self):
        val = self.count
        self.count += 1
        return val

def format_diagram_section(title: str, mmd_code: str, counter: SectionCounter) -> str:
    if not mmd_code:
        return ""
    return f"""
    <h2>{counter.next()}. {title}</h2>
    <div class="mermaid">
        {mmd_code}
    </div>
    """

def format_governed_interface_contracts(mod_toml: dict, global_locks: dict, module_name: str, counter: SectionCounter) -> str:
    """Merges Public API and Interface Contracts into a single governed section."""
    exposed = mod_toml.get("public_api", {}).get("exposed", [])
    local_locks = mod_toml.get("interface_lock", {})
    all_locks = {**global_locks, **local_locks}
    
    # Filter locks that belong to this module
    locks_by_file = {}
    for path, data in all_locks.items():
        if path.startswith(module_name):
            locks_by_file[path] = data

    if not exposed and not locks_by_file:
        return ""
    
    sections = [f"<h2>{counter.next()}. Governed Interface Contracts</h2>"]
    sections.append("<p>Interfaces listed below are governed by signature locks. Exposing an API implies a mandatory lock.</p>")

    # Create lookup from full locked name to its spec and path
    locked_name_to_spec = {}
    for path, data in locks_by_file.items():
        for func_name in data.get("locked_functions", []):
            locked_name_to_spec[func_name] = (path, func_name, data.get("specs", {}).get(func_name))

    # A helper to check if a name is public (exposed or class method of exposed class)
    def check_is_public(name: str) -> bool:
        name_lower = name.lower()
        exposed_lower = [e.lower() for e in exposed]
        if name_lower in exposed_lower:
            return True
        if "." in name:
            parts = name_lower.split(".")
            if parts[0] in exposed_lower:
                return True
        return False

    # Build the grouped structure
    governed_groups = {}
    
    # 1. Process all locked functions
    for func_name, (path, _, spec) in locked_name_to_spec.items():
        if not check_is_public(func_name):
            continue
            
        if "." in func_name:
            class_name, method_name = func_name.split(".", 1)
            # Find existing class group case-insensitively
            matched_class = class_name
            for g_name in governed_groups.keys():
                if g_name.lower() == class_name.lower():
                    matched_class = g_name
                    break
            if matched_class not in governed_groups:
                governed_groups[matched_class] = {
                    "type": "class",
                    "path": path,
                    "description": "",
                    "methods": {}
                }
            governed_groups[matched_class]["methods"][method_name] = spec
        else:
            spec_desc = spec.get("description", "") if spec else ""
            governed_groups[func_name] = {
                "type": "function",
                "path": path,
                "description": spec_desc,
                "spec": spec
            }

    # 2. Add exposed items that aren't locked but exist in exposed
    for exp_name in exposed:
        matched_group_key = None
        for g_name in governed_groups.keys():
            if g_name.lower() == exp_name.lower():
                matched_group_key = g_name
                break
                
        if matched_group_key is None:
            has_methods_locked = any(k.lower().startswith(exp_name.lower() + ".") for k in locked_name_to_spec.keys())
            if not has_methods_locked:
                guessed_path = "Unknown"
                if locks_by_file:
                    guessed_path = list(locks_by_file.keys())[0]
                
                # Check case-insensitively if exp_name has a direct lock spec
                spec = None
                matched_lock_key = None
                for k in locked_name_to_spec.keys():
                    if k.lower() == exp_name.lower():
                        matched_lock_key = k
                        break
                if matched_lock_key:
                    guessed_path, _, spec = locked_name_to_spec[matched_lock_key]
                
                spec_desc = spec.get("description", "") if spec else ""
                governed_groups[exp_name] = {
                    "type": "class" if exp_name[0].isupper() else "function",
                    "path": guessed_path,
                    "description": spec_desc,
                    "spec": spec
                }

    # 3. Pull descriptions from spec keys matching parent name directly.
    # We use a fallback cascade to prevent empty descriptions:
    # Spec Description -> Returns Description -> File Lock Reason
    # We allow case-insensitive matching here solely to map instance singletons (e.g., lowercase "notifier")
    # to their parent classes (e.g., uppercase "Notifier") in visual reports.
    for name, group in governed_groups.items():
        for path, data in locks_by_file.items():
            specs = data.get("specs", {})
            for spec_key in specs.keys():
                if spec_key.lower() == name.lower():
                    spec_data = specs[spec_key]
                    desc = spec_data.get("description", "")
                    if not desc:
                        desc = spec_data.get("returns", {}).get("description", "")
                    if desc:
                        group["description"] = desc

        # Fallback: Use the file lock's general reason if no specific function/class description is found
        if not group["description"]:
            for path, data in locks_by_file.items():
                locked_fns_lower = [k.lower() for k in data.get("locked_functions", [])]
                if name.lower() in locked_fns_lower or any(k.startswith(name.lower() + ".") for k in locked_fns_lower):
                    group["description"] = data.get("reason", "")
                    break

    sections.append("<table><thead><tr><th>Function/Class</th><th>Source File</th><th>Description</th></tr></thead><tbody>")
    
    for name in sorted(governed_groups.keys()):
        group = governed_groups[name]
        path = group["path"]
        desc = group["description"]
        
        # Determine if there are detailed specs in the group
        has_specs = False
        if group["type"] == "class" and "methods" in group:
            has_specs = any(group["methods"].values())
        elif "spec" in group and group["spec"]:
            has_specs = True
            
        if path != "Unknown":
            display_link = f'<a href="#contract-{safe_id(name)}"><code>{name}</code></a>' if has_specs else f'<code>{name}</code>'
            sections.append(f'<tr><td>{display_link}</td><td><code>{esc(path)}</code></td><td>{esc(desc)}</td></tr>')
        else:
            sections.append(f'<tr><td><code>{esc(name)}</code></td><td><small><em>Unknown</em></small></td><td>{esc(desc)}</td></tr>')
            
    sections.append("</tbody></table>")

    # Detailed specs for those that have them
    for name in sorted(governed_groups.keys()):
        group = governed_groups[name]
        path = group["path"]
        
        has_specs = False
        if group["type"] == "class" and "methods" in group:
            has_specs = any(group["methods"].values())
        elif "spec" in group and group["spec"]:
            has_specs = True
            
        if not has_specs:
            continue
            
        sections.append(f"<h3 id=\"contract-{safe_id(name)}\">Contract: <code>{esc(name)}</code></h3>")
        sections.append(f'<div class="lock-reason"><strong>Location:</strong> <code>{esc(path)}</code></div>')
        
        if group["type"] == "class" and "methods" in group:
            # Render each method
            for method_name, spec in sorted(group["methods"].items()):
                if not spec:
                    continue
                sections.append(f"<h4>Method: <code>{esc(method_name)}</code></h4>")
                sections.append('<div class="spec-box">')
                if "params" in spec:
                    sections.append('<table><thead><tr><th>Parameter</th><th>Type</th><th>Default</th><th>Description</th></tr></thead><tbody>')
                    for p in spec["params"]:
                        sections.append(f'<tr><td><span class="badge badge-param">{esc(p.get("name"))}</span></td>')
                        sections.append(f'<td><span class="badge badge-type">{esc(p.get("type"))}</span></td>')
                        sections.append(f'<td><code>{esc(p.get("default"))}</code></td>')
                        sections.append(f'<td>{esc(p.get("description"))}</td></tr>')
                    sections.append('</tbody></table>')
                
                ret = spec.get("returns", {})
                if ret:
                    sections.append(f'<p><strong>Returns:</strong> <code>{esc(ret.get("type"))}</code> - {esc(ret.get("description"))}</p>')
                    if "required_keys" in ret:
                        sections.append(f'<p><strong>Required Keys:</strong> <code>{esc(json.dumps(ret["required_keys"]))}</code></p>')
                    if "required_columns" in ret:
                        sections.append(f'<p><strong>Required Columns:</strong> <code>{esc(json.dumps(ret["required_columns"]))}</code></p>')
                sections.append('</div>')
        else:
            # Standalone function or enum spec
            spec = group["spec"]
            sections.append('<div class="spec-box">')
            if "params" in spec:
                sections.append('<table><thead><tr><th>Parameter</th><th>Type</th><th>Default</th><th>Description</th></tr></thead><tbody>')
                for p in spec["params"]:
                    sections.append(f'<tr><td><span class="badge badge-param">{esc(p.get("name"))}</span></td>')
                    sections.append(f'<td><span class="badge badge-type">{esc(p.get("type"))}</span></td>')
                    sections.append(f'<td><code>{esc(p.get("default"))}</code></td>')
                    sections.append(f'<td>{esc(p.get("description"))}</td></tr>')
                sections.append('</tbody></table>')
            
            ret = spec.get("returns", {})
            if ret:
                sections.append(f'<p><strong>Returns:</strong> <code>{esc(ret.get("type"))}</code> - {esc(ret.get("description"))}</p>')
                if "required_keys" in ret:
                    sections.append(f'<p><strong>Required Keys:</strong> <code>{esc(json.dumps(ret["required_keys"]))}</code></p>')
                if "required_columns" in ret:
                    sections.append(f'<p><strong>Required Columns:</strong> <code>{esc(json.dumps(ret["required_columns"]))}</code></p>')
            sections.append('</div>')
    
    return "".join(sections)


def format_invariants(invariants: dict, module_name: str, counter: SectionCounter) -> str:
    if not invariants:
        return ""
    
    sections = [f"<h2>{counter.next()}. Semantic Invariants (🔴 Red Lines)</h2>"]
    
    for cat, data in invariants.items():
        sections.append(f"<h3>Category: {esc(cat.replace('_', ' ').title())}</h3><ul>")
        for rule in data.get("rules", []):
            if isinstance(rule, str):
                sections.append(f"<li>{esc(rule)}</li>")
            else:
                rule_id = rule.get("id", "")
                sections.append(f'<li id="invariant-{safe_id(rule_id)}"><span class="invariant-id">[{esc(rule_id)}]</span> {esc(rule.get("desc"))}')
                if "test_ref" in rule:
                    sections.append(f'<br/><small>Verified by: <code>{esc(rule["test_ref"])}</code></small>')
                sections.append("</li>")
        sections.append("</ul>")
    
    return "".join(sections)


# ── Core Flows & Algorithms ([[design.flows]]) ────────────────────────

DESIGN_FLOW_KINDS = {"flow", "gates", "priority", "principles"}


def _mmd_esc(value: Any) -> str:
    """Escape text embedded in a Mermaid HTML node label."""
    return (str(value)
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "#quot;"))


def _contract_anchor(name: str) -> str:
    """Anchor of the interface-contract section for a function/class name."""
    cls = str(name).split(".")[0]
    return f"contract-{safe_id(cls)}"


def _mmd_anchor(text: str, href: str) -> str:
    return f"<a href='{href}'>{_mmd_esc(text)}</a>"


def _step_refs_html(step: dict, lookup: dict | None = None) -> str:
    """Related-function and invariant hyperlinks for a design step.

    A dead link degrades to plain <code> text (no <a href>) so the HTML
    never breaks on unresolved references; the resolve test fails instead.
    """
    parts = []
    ref = step.get("ref")
    if ref:
        refs = ref if isinstance(ref, list) else [ref]
        for r in refs:
            if lookup is not None and not lookup["ref_ok"](r):
                parts.append(f"<code>{esc(r)}</code>")
            else:
                parts.append(f'<a class="design-ref" href="#{_contract_anchor(r)}"><code>{esc(r)}</code></a>')
    inv = step.get("invariant")
    if inv:
        invs = inv if isinstance(inv, list) else [inv]
        for i in invs:
            if lookup is not None and i not in lookup["inv_ok"]:
                parts.append(f"<code>{esc(i)}</code>")
            else:
                parts.append(f'<a class="design-ref" href="#invariant-{safe_id(i)}"><code>{esc(i)}</code></a>')
    constraint = step.get("constraint")
    if constraint:
        parts.append(f"<small><em>{esc(constraint)}</em></small>")
    return " &middot; ".join(parts)


def _design_flow_mermaid(block: dict, lookup: dict | None = None) -> str:
    """kind=flow → Mermaid flowchart TD with sequential step nodes."""
    steps = block.get("steps", [])
    if not steps:
        return ""
    flow_id = safe_id(str(block.get("id", "flow")))
    lines = ["graph TD", f"    %% {flow_id} — linear flow"]
    prev = None
    for i, step in enumerate(steps):
        nid = f"df_{flow_id}_{i}"
        label_parts = [f"<b>{_mmd_esc(step.get('seq', i + 1))}. {_mmd_esc(step.get('title', ''))}</b>"]
        desc = step.get("desc")
        if desc:
            label_parts.append(f"<small><i>{_mmd_esc(desc)}</i></small>")
        check = step.get("check")
        if check:
            label_parts.append(f"<small><b>check:</b> <code>{_mmd_esc(check)}</code></small>")
        ref = step.get("ref")
        if ref:
            refs = ref if isinstance(ref, list) else [ref]
            ref_links = [
                _mmd_anchor(r, f"#{_contract_anchor(r)}")
                if lookup is None or lookup["ref_ok"](r)
                else _mmd_esc(r)
                for r in refs
            ]
            label_parts.append("<small>" + " &middot; ".join(ref_links) + "</small>")
        inv = step.get("invariant")
        if inv:
            invs = inv if isinstance(inv, list) else [inv]
            inv_links = [
                _mmd_anchor(i, f"#invariant-{safe_id(i)}")
                if lookup is None or i in lookup["inv_ok"]
                else _mmd_esc(i)
                for i in invs
            ]
            label_parts.append("<small>" + " &middot; ".join(inv_links) + "</small>")
        label = "<br/>".join(label_parts)
        lines.append(f'    {nid}["{label}"]')
        if prev:
            lines.append(f"    {prev} --> {nid}")
        prev = nid
    lines.append("    classDef flowPhase fill:#E8F5E9,stroke:#2E7D32,stroke-width:2px,color:#1B5E20;")
    return "\n".join(lines)


def _design_gates_table(steps: list, lookup: dict | None = None) -> str:
    rows = []
    for i, step in enumerate(steps):
        rows.append(
            "<tr>"
            f'<td><span class="badge badge-gate">{esc(step.get("seq", i + 1))}</span></td>'
            f"<td><strong>{esc(step.get('title', ''))}</strong></td>"
            f'<td><code>{esc(step.get("check", ""))}</code></td>'
            f"<td>{_step_refs_html(step, lookup)}</td>"
            "</tr>"
        )
    return ("<table><thead><tr><th>#</th><th>Gate</th><th>Check</th><th>Refs</th></tr></thead><tbody>"
            + "".join(rows) + "</tbody></table>")


def _design_priority_table(steps: list, lookup: dict | None = None) -> str:
    prio_classes = {"P0": "badge-p0", "P1": "badge-p1", "P2": "badge-p2", "P3": "badge-p3"}
    rows = []
    for i, step in enumerate(steps):
        prio = str(step.get("priority", ""))
        badge = prio_classes.get(prio.upper(), "badge-gate")
        prio_html = f'<span class="badge {badge}">{esc(prio)}</span>' if prio else ""
        rows.append(
            "<tr>"
            f'<td><span class="badge badge-gate">{esc(step.get("seq", i + 1))}</span></td>'
            f"<td>{prio_html}</td>"
            f"<td><strong>{esc(step.get('title', ''))}</strong></td>"
            f'<td><code>{esc(step.get("check", ""))}</code></td>'
            f"<td>{_step_refs_html(step, lookup)}</td>"
            "</tr>"
        )
    return ("<table><thead><tr><th>#</th><th>Priority</th><th>Phase</th><th>Trigger / Action</th><th>Refs</th></tr></thead><tbody>"
            + "".join(rows) + "</tbody></table>")


def _design_principles_cards(steps: list, lookup: dict | None = None) -> str:
    parts = []
    for i, step in enumerate(steps):
        parts.append(
            '<div class="design-card">'
            f"<strong>{esc(step.get('seq', i + 1))}. {esc(step.get('title', ''))}</strong>"
            f'<p>{esc(step.get("desc", ""))}</p>'
            f'<div class="design-card-refs">{_step_refs_html(step, lookup)}</div>'
            "</div>"
        )
    return "".join(parts)


def _design_steps_list(steps: list) -> str:
    items = []
    for i, step in enumerate(steps):
        items.append(f"<li><strong>{esc(step.get('title', ''))}</strong> — {esc(step.get('desc', ''))}</li>")
    return "<ol>" + "".join(items) + "</ol>"


def _build_design_link_lookup(mod_toml: dict, module_name: str, global_locks: dict | None = None, global_invariants: dict | None = None) -> dict:
    """Sets of ref names / invariant ids that resolve to real HTML anchors.

    Mirrors format_governed_interface_contracts anchor selection: a ref is
    live iff its owning class/function is exposed AND carries at least one
    non-empty lock spec; an invariant id is live iff declared in the module
    or the architecture-wide invariant rules.
    """
    exposed = [e.lower() for e in mod_toml.get("public_api", {}).get("exposed", [])]
    all_locks = dict(global_locks or {})
    all_locks.update(mod_toml.get("interface_lock", {}))
    specs_map = {}
    for path, data in all_locks.items():
        if path.startswith(module_name):
            for spec_key, spec in data.get("specs", {}).items():
                specs_map[spec_key.lower()] = spec

    def ref_ok(r: str) -> bool:
        cls = str(r).split(".")[0].lower()
        if cls not in exposed:
            return False
        if "." in str(r):
            return any(k.startswith(cls + ".") and specs_map[k] for k in specs_map)
        return any(k == cls and specs_map[k] for k in specs_map)

    inv_ok: set[str] = set()
    for inv in (global_invariants or {}, mod_toml.get("invariant", {})):
        for cat, data in inv.items():
            for rule in data.get("rules", []):
                if isinstance(rule, dict) and rule.get("id"):
                    inv_ok.add(rule["id"])

    return {"ref_ok": ref_ok, "inv_ok": inv_ok}


def format_design_section(mod_toml: dict, counter: SectionCounter, lookup: dict | None = None) -> str:
    """Render the optional [[design.flows]] chapter (Core Flows & Algorithms)."""
    flows = mod_toml.get("design", {}).get("flows", [])
    if not flows:
        return ""
    sections = [f"<h2>{counter.next()}. Core Flows & Algorithms</h2>"]

    for block in flows:
        block_id = block.get("id", "")
        anchor = f' id="design-{safe_id(block_id)}"' if block_id else ""
        sections.append(f"<h3{anchor}>{esc(block.get('title', ''))}</h3>")
        if block.get("summary"):
            sections.append(f"<p><em>{esc(block['summary'])}</em></p>")
        steps = block.get("steps", [])
        if not steps:
            continue
        kind = block.get("kind", "")
        if kind == "flow":
            mmd = _design_flow_mermaid(block, lookup)
            sections.append(f'<div class="mermaid">{mmd}</div>' if mmd else _design_steps_list(steps))
        elif kind == "gates":
            sections.append(_design_gates_table(steps, lookup))
        elif kind == "priority":
            sections.append(_design_priority_table(steps, lookup))
        elif kind == "principles":
            sections.append(_design_principles_cards(steps, lookup))
        else:
            sections.append(_design_steps_list(steps))
    return "".join(sections)


# ── Main ────────────────────────────────────────────────────────────

def discover_all_modules(base_dir: Path, submodules_list: list[str]) -> set[str]:
    """Recursively discover all module directories that have a module.toml."""
    discovered = set()
    for sub in submodules_list:
        sub_path = base_dir / sub
        if sub_path.is_dir():
            mod_toml = sub_path / "module.toml"
            if mod_toml.exists():
                rel_path = sub_path.relative_to(PROJECT_ROOT).as_posix()
                discovered.add(rel_path)
                with open(mod_toml, "rb") as f:
                    try:
                        cfg = tomllib.load(f)
                        inner_subs = cfg.get("module", {}).get("submodules", [])
                        discovered.update(discover_all_modules(sub_path, inner_subs))
                    except Exception:
                        pass
    return discovered


def get_module_depends_on(module_name: str, arch: dict) -> list[str]:
    """Get the depends_on list for any module (top-level or submodule)."""
    if "/" not in module_name:
        cfg = arch.get("module", {}).get(module_name, {})
        return list(cfg.get("depends_on", []))
    
    parts = module_name.split("/")
    parent_name = "/".join(parts[:-1])
    child_name = parts[-1]
    
    parent_toml_path = PROJECT_ROOT / parent_name / "module.toml"
    if parent_toml_path.exists():
        with open(parent_toml_path, "rb") as f:
            try:
                p_cfg = tomllib.load(f)
                sub_cfg = p_cfg.get("submodule", {}).get(child_name, {})
                return list(sub_cfg.get("depends_on", [])) + list(sub_cfg.get("external_depends", []))
            except Exception:
                pass
    return []


def main() -> None:
    ASSETS_DIR.mkdir(parents=True, exist_ok=True)
    arch = _load_architecture()
    modules = arch.get("module", {})
    global_locks = arch.get("interface_lock", {})
    global_invariants = arch.get("invariant", {})

    # 1. Global architecture-full.html
    full_mmd = generate_architecture_full_mmd(arch)
    full_counter = SectionCounter()
    full_content = []
    full_content.append(format_diagram_section("Architecture Design (Design Intent)", full_mmd, full_counter))
    full_content.append(format_invariants(global_invariants, "", full_counter))
    
    full_html = HTML_TEMPLATE.format(
        title="Full Architecture",
        header="System-Wide Architecture",
        description="Top-level module dependencies and design intent.",
        content_sections="".join(full_content),
        timestamp=_get_timestamp()
    )
    (ASSETS_DIR / "architecture-full.html").write_text(full_html, encoding="utf-8")
    print("Generated architecture-full.html")

    # Discover all modules recursively
    all_modules = discover_all_modules(PROJECT_ROOT, arch.get("submodules", []))
    for key in modules.keys():
        all_modules.add(key)

    # 2. Per-module HTML
    for mod_name in sorted(all_modules):
        mod_dir = PROJECT_ROOT / mod_name
        mod_toml = _load_module_toml(mod_dir) if mod_dir.is_dir() else {}
        
        locks = mod_toml.get("interface_lock", {})
        if not locks:
            locks = global_locks
        else:
            for k, v in global_locks.items():
                if k.startswith(mod_name):
                    locks[k] = v

        invariants = mod_toml.get("invariant", {})

        # Unified architecture diagram (includes both internal and external dependencies)
        internal_mmd = generate_module_internal_mmd(mod_name, mod_toml)
        
        mod_counter = SectionCounter()
        content = []
        content.append(format_metadata_section(mod_toml, mod_counter))
        content.append(format_diagram_section("Architecture & Dependencies", internal_mmd, mod_counter))
        design_lookup = _build_design_link_lookup(mod_toml, mod_name, global_locks, global_invariants)
        content.append(format_design_section(mod_toml, mod_counter, lookup=design_lookup))
        content.append(format_governed_interface_contracts(mod_toml, global_locks, mod_name, mod_counter))
        content.append(format_invariants(invariants, mod_name, mod_counter))
        
        safe_name = mod_name.replace("/", "-")
        header_desc = f"Architecture governance and interface contracts for module: {mod_name}."

        mod_html = HTML_TEMPLATE.format(
            title=f"Module: {esc(mod_name)}",
            header=f"Module: {esc(mod_name)}",
            description=esc(header_desc),
            content_sections="".join(content),
            timestamp=_get_timestamp()
        )
        (ASSETS_DIR / f"{safe_name}.html").write_text(mod_html, encoding="utf-8")
        print(f"Generated {safe_name}.html")

    # Cleanup old .mmd files
    for mmd_file in ASSETS_DIR.glob("*.mmd"):
        mmd_file.unlink()
        print(f"Removed legacy {mmd_file.name}")


if __name__ == "__main__":
    main()




